
### URL BASE
@api_base_url=https://services.odata.org/northwind/northwind.svc/

### Return results in json format
@json_format=$format=json

### Uncomment the line below if you want to return the results in OData format.
### @json_format=""


### Retrieve Orders with Customer Details
GET {{api_base_url}}Orders?{{json_format}}&$expand=Customer

### Retrieve Employees Reporting to Manager with ID 2
GET {{api_base_url}}Employees?{{json_format}}&$filter=ReportsTo%20eq%202

### Retrieve Products with Stock Available
GET {{api_base_url}}Products?{{json_format}}&$filter=UnitsInStock%20gt%200

### Retrieve Names and Codes of Products Out of Stock
GET {{api_base_url}}Products?{{json_format}}&$filter=UnitsInStock%20eq%200&$select=ProductName,ProductID

### Retrieve the Top 5 Most Expensive Products
GET {{api_base_url}}Products?{{json_format}}&$orderby=UnitPrice%20desc&$top=5

### Retrieve Orders Shipped to Germany
GET {{api_base_url}}Orders?{{json_format}}&$filter=ShipCountry%20eq%20'Germany'

### Retrieve Names and Prices of Products Shipped to Germany
GET {{api_base_url}}Order_Details?{{json_format}}&$expand=Product&$filter=Order/ShipCountry%20eq%20'Germany'&$select=Product/ProductName,Product/UnitPrice

